"""add column role to user model

Revision ID: 04130fd2ae87
Revises: 24452d0bf38c
Create Date: 2024-10-24 16:22:45.660928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04130fd2ae87'
down_revision = '24452d0bf38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
