"""add ondelete cascade on product, preduct_keys and sub_category models

Revision ID: 24452d0bf38c
Revises: f5ba25e0cdf0
Create Date: 2024-10-22 21:13:51.820063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24452d0bf38c'
down_revision = 'f5ba25e0cdf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_keys', schema=None) as batch_op:
        batch_op.create_foreign_key('keys', 'keys', ['key_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('products', 'products', ['product_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_foreign_key('sub_categories', 'sub_categories', ['sub_category_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('platforms', 'platforms', ['platform_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('categories', 'categories', ['category_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('sub_categories', schema=None) as batch_op:
        batch_op.create_foreign_key('categories', 'categories', ['category_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_categories', schema=None) as batch_op:
        batch_op.create_foreign_key('categories', 'categories', ['category_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_foreign_key('sub_categories', 'sub_categories', ['sub_category_id'], ['id'])
        batch_op.create_foreign_key('categories', 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key('platforms', 'platforms', ['platform_id'], ['id'])

    with op.batch_alter_table('product_keys', schema=None) as batch_op:
        batch_op.create_foreign_key('keys', 'keys', ['key_id'], ['id'])
        batch_op.create_foreign_key('products', 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###
