"""add price in key model

Revision ID: f5ba25e0cdf0
Revises: 
Create Date: 2024-10-22 17:59:09.843947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ba25e0cdf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
